<?php

namespace AppBundle\Repositery;

use Doctrine\ORM\EntityRepository;

/**
 * PostRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class PostRepository extends EntityRepository
{
}
