<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Post;
use Doctrine\ORM\EntityRepository;

/**
 * PostRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class PostRepository extends EntityRepository
{
    /**
     * @return Post[]
     */
    public function findAllPublishedOrderedByDate(){
        return $this->createQueryBuilder('post')
            ->andWhere('post.published = :published')
            ->setParameter('published', true)
            ->orderBy('post.date_updated', 'DESC')
            ->getQuery()
            ->execute();
    }
}
