# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    quote_generator:
        class: AppBundle\Service\QuoteGenerator
        arguments: ['@logger']

    markdown_transformer:
        class: AppBundle\Service\MarkdownTransformer
        arguments: ['@markdown.parser', '@doctrine_cache.providers.my_markdown_cache']

    markdownify_extension:
        class: AppBundle\Twig\MarkdownExtension
        tags:
            - { name: twig.extension }
        #arguments: ['@markdown_transformer']
        autowire: true